packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@clerk/shared': true
  '@iamjariwala/react-doc-viewer': true
  '@prisma/engines': true
  canvas: true
  esbuild: false
  msw: false
  prisma: true
catalogs:
  prisma:
    prisma: latest
