packages:
  - apps/frontend
  - apps/backend
allowBuilds:
  '@clerk/shared': true
  '@iamjariwala/react-doc-viewer': false
  '@prisma/engines': true
  canvas: false
  esbuild: false
  msw: false
  prisma: true
